#Expyriment 1.0.0 (Python 3.13.7), .xpe-file, coding: UTF-8
#date: Sat Sep 20 2025 21:39:02
#sha1: 407fb9
#modules: 
#display: size=(800, 600), window_mode=True, opengl=2
#os: uname_result(system='Darwin', node='YixuandeMacBook-Air.local', release='24.6.0', version='Darwin Kernel Version 24.6.0: Mon Jul 14 11:30:40 PDT 2025; root:xnu-11417.140.69~1/RELEASE_ARM64_T8132', machine='arm64')
Time,Type,Event,Value,Detail,Detail2
489,stderr,received,'Traceback (most recent call last):'
489,stderr,received,'  File "/Users/yixuanzhu/Documents/CogSup/Programming/Assignments/Week-2/Exercises/labeled_shapes.py", line 12, in <module>\n    left_square = extras.PolygonLine(\n        size=(50),colour=(255, 0, 0), position=(-100, 0)\n    )'
489,stderr,received,"TypeError: PolygonLine.__init__() got an unexpected keyword argument 'size'"
